name: Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm install

      - name: Set Short GitHub SHA
        id: short-sha
        run: |
          shortSHA=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=sha::$shortSHA"

      - name: Build vsix
        run: npx vsce package -o api-insights-vscode-${{ steps.short-sha.outputs.sha }}.vsix

      - uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"

  integration:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3

      - name: Check AWS CLI
        run: aws --version

      - name: Upload to AWS S3
        run: aws s3 sync ./artifact s3://${{ secrets.AWS_BUCKET }}/${{ secrets.AWS_FOLDER }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2